_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
modelname:
    value: etcaps
num_datapoints:
    value: 10
output_dir:
    value: li
